@startmindmap
* Ментальные ловушки

** Упорство

** Амплификация (вкладывание в достижение цели больше усилий, чем нужно)

** Фиксация

** Реверсия

** Опережение

** Противление

** Затягивание

** Разделение

** Ускорение

** Регулирование

** Формулирование

@endmindmap